options: { logging: CLOUD_LOGGING_ONLY, substitutionOption: ALLOW_LOOSE }
substitutions:
  _SERVICE_NAME: finops-controller
  _REGION: us-central1
  _AR_REPO: finops-app
  _RUNTIME_SA_EMAIL: finops-runtime@${PROJECT_ID}.iam.gserviceaccount.com
  _BQ_DATASET: finops_curated
  _BQ_ALERTS_TABLE: cur_alerts

steps:
- id: "Build container"
  name: gcr.io/cloud-builders/docker
  dir: app
  args:
    ["build","-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA","."]

- id: "Push image"
  name: gcr.io/cloud-builders/docker
  args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA"]

- id: "Deploy to Cloud Run"
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    ["run","deploy","${_SERVICE_NAME}",
     "--image","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA",
     "--region","${_REGION}",
     "--service-account","${_RUNTIME_SA_EMAIL}",
     "--no-allow-unauthenticated",
     "--platform","managed",
     "--max-instances","3",
     "--set-env-vars","BQ_DATASET=${_BQ_DATASET},BQ_ALERTS_TABLE=${_BQ_ALERTS_TABLE}"]

images:
- "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA"
