options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

substitutions:
  _TF_DIR: "infra"                  # path to your TF code
  _TF_PLAN_FILE: "plan.tfplan"      # single source of truth
  _TF_PLAN_TXT: "plan.txt"
  _TF_VARS_FILE: "infra/terraform.tfvars"
  _CONTROLLER_IMAGE: ""             # value injected by app CD trigger

steps:
# (optional) keep .terraform warm
- name: gcr.io/cloud-builders/gsutil
  id: "warm-cache"
  entrypoint: bash
  args: ["-c", "mkdir -p /workspace/${_TF_DIR}/.terraform"]

- name: hashicorp/terraform:1.7.5
  id: "fmt"
  dir: ${_TF_DIR}
  entrypoint: sh
  args: ["-lc", "terraform fmt -recursive && echo 'fmt done'"]

- name: hashicorp/terraform:1.7.5
  id: "init"
  dir: ${_TF_DIR}
  args: ["init","-input=false"]

- name: hashicorp/terraform:1.7.5
  id: "validate"
  dir: ${_TF_DIR}
  args: ["validate","-no-color"]

- name: hashicorp/terraform:1.7.5
  id: "plan"
  dir: ${_TF_DIR}
  args:
    - "plan"
    - "-no-color"
    - "-input=false"
    - "-var=controller_image=${_CONTROLLER_IMAGE}"
    # If you want to use your tfvars file too, uncomment next line:
    # - "-var-file=${_TF_VARS_FILE}"
    - "-out=${_TF_PLAN_FILE}"

# human-readable plan (optional but super helpful)
- name: hashicorp/terraform:1.7.5
  id: "render-plan"
  dir: ${_TF_DIR}
  entrypoint: sh
  args:
    - -lc
    - |
      terraform show -no-color ${_TF_PLAN_FILE} > ${_TF_PLAN_TXT}
      echo "Wrote ${_TF_PLAN_TXT}"

artifacts:
  objects:
    location: "gs://$PROJECT_ID-tfstate/builds/${BUILD_ID}"
    paths:
      - "${_TF_DIR}/${_TF_PLAN_FILE}"
      - "${_TF_DIR}/${_TF_PLAN_TXT}"