options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

substitutions:
  _APP_DIR: "app"

steps:
- name: python:3.11
  id: "install"
  dir: ${_APP_DIR}
  entrypoint: bash
  args:
    - -lc
    - |
      python -m pip install --upgrade pip
      pip install -r requirements.txt || true
      # Ensure pytest exists even if you don't keep tests/requirements.txt
      pip install pytest
- name: python:3.11
  id: "pytest"
  dir: ${_APP_DIR}
  entrypoint: bash
  args:
    - -lc
    - |
      # If no tests, exit 0 so PR check passes
      if ! compgen -G "tests/test_*.py" > /dev/null; then
        echo "No tests found; skipping."
        exit 0
      fi
      python -m pytest -q --maxfail=1 --disable-warnings