# CI: run unit tests on PRs/commits, no deploys
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

substitutions:
  _APP_DIR: "app"
  _TFSTATE_BUCKET: "tfstate-optical-office-475814-t3-prod"
  

steps:
# 1) install deps
- name: python:3.11
  id: install
  dir: ${_APP_DIR}
  entrypoint: bash
  args:
    - -lc
    - |
      python -m pip install --upgrade pip
      pip install -r requirements.txt || true
      # ensure pytest exists even if you don't yet ship tests
      pip install pytest

# 2) run tests (skip cleanly if none exist)
- name: python:3.11
  id: pytest
  dir: ${_APP_DIR}
  entrypoint: bash
  args:
    - -lc
    - |
      if ! compgen -G "tests/test_*.py" >/dev/null; then
        echo "No tests found; skipping."
        exit 0
      fi
      python -m pytest -q --maxfail=1 --disable-warnings