options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

substitutions:
  _APP_DIR: "app"
  _REGION: "us-central1"
  _AR_REPO: "finops-app"                       # Artifact Registry repo (Docker)
  _SERVICE_NAME: "finops-controller" 
  _IMAGE_NAME: "finops-controller"
  _INFRA_APPLY_TRIGGER_ID: "32968aa2-c552-4e70-b0e7-8da2d7db8b73"         # Cloud Run service name
  _RUNTIME_SA_EMAIL: "finops-runtime@${PROJECT_ID}.iam.gserviceaccount.com"

  # App config (non-secret)
  _BQ_DATASET: "finops_curated"
  _BQ_ALERTS_TABLE: "cur_alerts"

  # Secret Manager: Slack webhook secret name (no version here)
  _SLACK_SECRET_NAME: "finops-slack-webhook"

  # Image tag
  _IMAGE: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${SHORT_SHA}"

steps:
# 0) build
- name: gcr.io/cloud-builders/docker
  id: "build-image"
  args:
    - "build"
    - "-t"
    - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/finops-controller:${SHORT_SHA}"
    - "app"

# 1) push
- name: gcr.io/cloud-builders/docker
  id: "push-image"
  args:
    - "push"
    - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/finops-controller:${SHORT_SHA}"

# 2) resolve DIGEST and trigger infra-apply (passing the image)
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  id: "trigger-infra-apply"
  entrypoint: bash
  args:
    - -c
    - |
      set -euo pipefail
      # Build the tag you just pushed (adjust if you tag differently)
      IMAGE="us-central1-docker.pkg.dev/$PROJECT_ID/finops-app/finops-controller:${SHORT_SHA}"
      # Get the digest of that tag
      DIGEST="$(gcloud artifacts docker images describe "$IMAGE" --format='get(image_summary.digest)')"
      FULL_IMAGE="${IMAGE%@*}@${DIGEST}"

      # Trigger infra-apply and pass the image to Terraform
      gcloud builds triggers run "$_INFRA_APPLY_TRIGGER_ID" \
        --branch=main \
        --substitutions=_CONTROLLER_IMAGE="$FULL_IMAGE"
        