options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

substitutions:
  _APP_DIR: "app"
  _TFSTATE_BUCKET: "tfstate-optical-office-475814-t3-prod"
  _REGION: "us-central1"
  _AR_REPO: "finops-app"                       # Artifact Registry repo (Docker)
  _SERVICE_NAME: "finops-controller" 
  _IMAGE_NAME: "finops-controller"
  _INFRA_APPLY_TRIGGER_ID: "32968aa2-c552-4e70-b0e7-8da2d7db8b73"         # Cloud Run service name
  _RUNTIME_SA_EMAIL: "finops-runtime@${PROJECT_ID}.iam.gserviceaccount.com"

  # App config (non-secret)
  _BQ_DATASET: "finops_curated"
  _BQ_ALERTS_TABLE: "cur_alerts"

  # Secret Manager: Slack webhook secret name (no version here)
  _SLACK_SECRET_NAME: "finops-slack-webhook"

  # Image tag
  _IMAGE_TAG: "${SHORT_SHA}"

steps:
  # 0) build
  - name: gcr.io/cloud-builders/docker
    id: build-image
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${_IMAGE_TAG}
      - ${_APP_DIR}

  # 1) push
  - name: gcr.io/cloud-builders/docker
    id: push-image
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${_IMAGE_TAG}
  
  - name: gcr.io/cloud-builders/docker
    id: "tag-latest"
    args: ["tag",
           "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${_IMAGE_TAG}",
           "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:latest"]

  - name: gcr.io/cloud-builders/docker
    id: "push-latest"
    args: ["push",
           "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:latest"]

    # 2) resolve digest and trigger infra-apply
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: trigger-infra-apply
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        REPO_PATH="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}"
        TAGGED_IMAGE="$${REPO_PATH}:${_IMAGE_TAG}"

        DIGEST="$(gcloud artifacts docker images describe "$$TAGGED_IMAGE" --format='value(image_summary.digest)')"
        FULL_IMAGE="$${REPO_PATH}@$${DIGEST}"
        echo "Using controller image: $$FULL_IMAGE"

        gcloud builds triggers run "$_INFRA_APPLY_TRIGGER_ID" \
          --region="${_REGION}" \
          --project="${PROJECT_ID}" \
          --branch="main" \
          --substitutions=_CONTROLLER_IMAGE="$$FULL_IMAGE"

