options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

substitutions:
  _APP_DIR: "app"
  _REGION: "us-central1"
  _AR_REPO: "finops-app"                       # Artifact Registry repo (Docker)
  _SERVICE_NAME: "finops-controller" 
  _IMAGE_NAME: "finops-controller"
  _INFRA_APPLY_TRIGGER_ID: "32968aa2-c552-4e70-b0e7-8da2d7db8b73"         # Cloud Run service name
  _RUNTIME_SA_EMAIL: "finops-runtime@${PROJECT_ID}.iam.gserviceaccount.com"

  # App config (non-secret)
  _BQ_DATASET: "finops_curated"
  _BQ_ALERTS_TABLE: "cur_alerts"

  # Secret Manager: Slack webhook secret name (no version here)
  _SLACK_SECRET_NAME: "finops-slack-webhook"

  # Image tag
  _IMAGE_TAG: "${SHORT_SHA}"

steps:
# 0) build
steps:
- name: gcr.io/cloud-builders/docker
  id: build-image
  args:
    - build
    - -t
    - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${_IMAGE_TAG}
    - ${_APP_DIR}

# 1) push
- name: gcr.io/cloud-builders/docker
  id: push-image
  args:
    - push
    - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${_IMAGE_TAG}

# 2) resolve digest and trigger infra-apply
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  id: trigger-infra-apply
  entrypoint: bash
  args:
    - -lc
    - |
      set -euo pipefail

      # base repo (no tag, no digest)
      IMG_REPO="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}"
      TAG="${_IMAGE_TAG}"

      # get the digest for the tag we just pushed
      DIGEST="$(gcloud artifacts docker images describe "${IMG_REPO}:${TAG}" \
        --format='value(image_summary.digest)')"

      if [[ -z "${DIGEST}" ]]; then
        echo "Failed to resolve image digest for ${IMG_REPO}:${TAG}" >&2
        exit 1
      fi

      FULL_IMAGE="${IMG_REPO}@${DIGEST}"
      echo "Resolved controller image: ${FULL_IMAGE}"

      # trigger infra-apply and pass image to Terraform
      gcloud builds triggers run "${_INFRA_APPLY_TRIGGER_ID}" \
        --branch=main \
        --substitutions=_CONTROLLER_IMAGE="${FULL_IMAGE}"